import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import { ColorModeProvider } from "@/components/ui/color-mode";
import { ThemeProvider } from "@/theme";
import { Box, Container, Flex, Heading, Text } from "@chakra-ui/react";
import type { Metadata } from "next";
import { JetBrains_Mono, Roboto_Flex, Roboto_Slab } from "next/font/google";
import Script from "next/script";

const headingFont = Roboto_Slab({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-heading",
    display: "swap",
});

const bodyFont = Roboto_Flex({
    subsets: ["latin"],
    variable: "--font-body",
    display: "swap",
});

const monoFont = JetBrains_Mono({
    subsets: ["latin"],
    weight: ["400"],
    variable: "--font-mono",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
    const { children } = props;
    return (
        <html
            suppressHydrationWarning={true}
            lang="en"
            className={`${headingFont.className} ${bodyFont.className} ${monoFont.className}`}>
            <head>
                <style>
                    {`
                :root {
                    --font-heading: ${headingFont.style.fontFamily};
                    --font-body: ${bodyFont.style.fontFamily};
                    --font-mono: ${monoFont.style.fontFamily};
                }
            `}
                </style>
            </head>
            <body>
                <Script
                    src="https://t.contentsquare.net/uxa/33a640938ca72.js"
                    strategy="afterInteractive"
                />
                <ColorModeProvider>
                    <ThemeProvider>
                        <Flex
                            direction="column"
                            textStyle="body"
                            minH="100vh"
                            maxW="100vw"
                            bg="bg.panel">
                            <Container maxW="4xl" py={2} as="header" w="100%">
                                <Heading
                                    textStyle="heading"
                                    fontSize="4xl"
                                    textDecoration="underline"
                                    textDecorationColor="teal"
                                    textDecorationStyle="wavy"
                                    m={0}>
                                    Colby Cooper
                                </Heading>
                                <Text fontSize="lg" color="fg.muted">
                                    Technical Problem-Solver & Developer
                                </Text>
                            </Container>
                            <Navbar />
                            <Box
                                flexGrow={1}
                                as="main"
                                w="100%"
                                mb={6}
                                overflowX="hidden"
                                overflowY="auto">
                                {children}
                            </Box>
                            <Footer />
                        </Flex>
                    </ThemeProvider>
                </ColorModeProvider>
            </body>
        </html>
    );
}
